### ISSUE TITLE
Execute all Validate() on embedded structs

### ISSUE THREAD

**Issue by Rudde** [SladeThe/yav#1]
Go support embedded structs like so:

```
type JsonValidationBody struct {
	RequiredInt int     `json:"required_int"`
	OptionalInt *int    `json:"optional_int"`
	RequiredStr string  `json:"required_str"`
	OptionalStr *string `json:"optional_str"`
	QueryParams
}

type QueryParams struct {
	QueryStr string `form:"query_str"`
}
```

Given the validators 

```
func (e JsonValidationBody) Validate() error {
	return yav.Join(
		yav.Chain(
			"required_int", e.RequiredInt,
			vnumber.Required[int],
		),
		yav.Chain(
			"required_str", e.RequiredStr,
			vstring.Required))
}

func (e QueryParams) Validate() error {
	return yav.Join(
		yav.Chain(
			"query_str", e.QueryStr,
			vstring.Required))
}
```

Would it be possible to get `QueryParams`'s Validate to execute when the `Validate()` on `JsonValidationBody ` is executed? Given that `QueryParams` can contain `n` elements to validate, it would be super helpful not having to reimplement them all every place the embedded struct is used.

**Comment by SladeThe** [comment]
Hey! You don't have to reimplement all the field validators, just call the embedded struct's `Validate()`.

```
func (e JsonValidationBody) Validate() error {
	return yav.Join(..., e.QueryParams.Validate())
}
```
All the `QueryParams` valdiation errors will be added to the common result as if `QueryStr` was in `JsonValidationBody` directly.

If a struct is not embedded, wrap `Validate()` with `yav.Nested`.

```
func (e JsonValidationBody) Validate() error {
	return yav.Join(..., yav.Nested("query", e.QueryParams.Validate()))
}
```
This adds "query." prefix to all the `QueryParams` errors, e.g. "query.query_str".

**Comment by SladeThe** [comment]
Also, I've recently added `vpointer` package for validating fields by pointer.

```go
yav.Chain(
	"optional_str", p.OptionalStr,
	vpointer.OmitEmpty[string], // Skip further validation, if pointer is nil.
	vpointer.Dereference[string](vstring.Required, ...), // This checks optional string is not empty, if pointer is not nil.
)
```
